# This project config file describes your project. See looper docs for details.
name: test_project # The name that summary files will be prefaced with    
pep_version: 2.0.0 
sample_table: samples_annotations.csv # sheet listing all samples in the project 
sample_modifiers:
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
